basePath: /v1
host: localhost:8080
info:
  contact:
    name: Andrew
    url: https://t.me/realPointer
  description: A service that will receive by api the full name, from open api enrich
    the response with the most probable age, gender and nationality and save the data
    in the db.
  title: EnrichInfo service
  version: 1.0.0
paths:
  /people:
    get:
      description: Returns a list of people matching the specified search criteria
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: Surname
        in: query
        name: surname
        type: string
      - description: Patronymic
        in: query
        name: patronymic
        type: string
      - description: Age
        in: query
        name: age
        type: integer
      - description: Gender
        in: query
        name: gender
        type: string
      - description: Nationality
        in: query
        name: nationality
        type: string
      - description: Page
        in: query
        name: page
        type: integer
      - description: Persons per page
        in: query
        name: perPage
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Search people
      tags:
      - People
      - People
    post:
      consumes:
      - application/json
      description: Get name, surname, patronymic, enrich with age, gender and nationality,
        and save to database
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
      summary: Create person
      tags:
      - People
  /people/{id}:
    delete:
      description: Delete person by id
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Delete person
      tags:
      - People
    put:
      consumes:
      - application/json
      description: Update person by id
      parameters:
      - description: Person ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
      summary: Update person
      tags:
      - People
swagger: "2.0"
